name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - matplotlib
  - scipy
  - numpy
  - matplotlib
  - unyt
  - pip:
    # - git+https://github.com/yt-project/yt_experiments.git@main
    - git+https://github.com/AnatoleStorck/yt_derived_fields.git@main
