name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - yt
  - matplotlib
  - unyt
  - pip
  - pip:
    - git+https://github.com/yt-project/yt_experiments/
    - git+https://github.com/AnatoleStorck/yt_derived_fields@main
